### ISSUE TITLE
cannot use engine

### ISSUE THREAD

**Issue by newyorkthink** [DanielMYT/tesseract-static#2]
![image](https://github.com/DanielMYT/tesseract-static/assets/87791643/3a590935-46d3-4b38-9639-048288382064)

**Comment by DanielMYT** [comment]
Hi, you have to obtain the training data for your desired language(s) and place it in your working directory. You can download the training data from the tessdata repo at [https://github.com/tesseract-ocr/tessdata](https://github.com/tesseract-ocr/tessdata). You only need to download the files corresponding to the languages you intend to use, for example `eng.traineddata` for English.

![image](https://github.com/DanielMYT/tesseract-static/assets/95963100/2028c629-bfc7-435c-82f2-f315f59ebf36)

**Comment by newyorkthink** [comment]
> Hi, you have to obtain the training data for your desired language(s) and place it in your working directory. You can download the training data from the tessdata repo at https://github.com/tesseract-ocr/tessdata. You only need to download the files corresponding to the languages you intend to use, for example `eng.traineddata` for English.
> 
> ![image](https://private-user-images.githubusercontent.com/95963100/324087069-2028c629-bfc7-435c-82f2-f315f59ebf36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3NDEsIm5iZiI6MTcxMzU5MTQ0MSwicGF0aCI6Ii85NTk2MzEwMC8zMjQwODcwNjktMjAyOGM2MjktYmZjNy00MzVjLTgyZjItZjMxNWY1OWViZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYTAwMDUzOWI1ZTYyYzAxZmJiMGZkZmVjMTc4OGU2MDE5MzAwZTg3MzIxMTdkOGVlMGZkNTNlYjVhMTBkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GuSlLMntbMx9tWnM-nDoglGJF0j5-gLajGalCdToV0)

cannot merge in pot translate software

**Comment by newyorkthink** [comment]
is this :https://github.com/pot-app/pot-desktop/releases/tag/2.7.10

**Comment by DanielMYT** [comment]
I'm unaware of that program, but you can specify the location of the data with the `TESSDATA_PREFIX` environment variable. For example, you could set it as you launch the external program, and that should apply:
```
TESSDATA_PREFIX="/home/username/tesseract/tessdata" myprogram
```
Or alternatively you could export it in a global shell startup file such as `.profile`, `.bash_profile` or `.bashrc` (the exact file depends on your distro - and you'll need to logout and log back in after making edits to those files), and that should allow graphical launches of the external program to support it:
```
export TESSDATA_PREFIX="/home/username/tesseract/tessdata"
```

![image](https://github.com/DanielMYT/tesseract-static/assets/95963100/ee7708e5-886a-4e53-aeb1-def5ff5d46ae)
